spring:
  application:
    name: CoinSec
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath*:xml/*Xml.xml

sa-token:
  token-name: coin-sec-token
  active-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: uuid