spring:
  application:
    name: Coinsec
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  mapper-locations: classpath*:xml/*Xml.xml

sa-token:
  token-name: coinsec-token
  token-style: uuid
  is-concurrent: true
  is-share: false